; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
;credit goes to vicky,soyal,shishir and other midas programmers.

#define MyAppName "MidasDrHoms_V3.2"
#define MyAppVersion "3.2"
#define MyAppPublisher "Midas Technology Pvt. Ltd."
#define MyAppURL "http://www.midas.com.np/"
#define MyAppExeName "MidasDrHomsV3_2.exe" 

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
;AppId={{5B509FEA-BEAD-48EA-AC82-3E30CA875E42}
AppId={{35F132B6-E374-4E18-9681-6D3844E02287}
AppName={#MyAppName}
AppVersion={#MyAppVersion}                   
;AppVerName={#MyAppName} {#MyAppVersion}                   
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\Midas DrHoms_V3.2
DefaultGroupName={#MyAppName}
WindowVisible=yes
OutputDir=.\
OutputBaseFilename=Midas DrHoms V3.2 Setup_NewClinicalModule
;SetupIconFile=E:\D10-icons\Icon.ico
Password=delphi10
Compression=lzma
SolidCompression=yes

[Code]

Var
     Edit:TEdit;
     FolderTreeView:TFolderTreeView;
     SourcePath,NotepadLocation:String;
     Dir_Loaded:Boolean;
     Page: TInputFileWizardPage;

Procedure LoadModule(Sender:Tobject);
begin
     FolderTreeView := TFolderTreeView.Create(WizardForm);
     FolderTreeView.Width := 300;
     FolderTreeView.Height := 250;
     FolderTreeView.Top:=10;
     FolderTreeView.Left:=WizardForm.WelcomeLabel2.Left;
     FolderTreeView.Parent := WizardForm;
     FolderTreeView.Directory := ExpandConstant('{src}');
     Dir_Loaded:=true;
end;

procedure CreateButton(ALeft, ATop: Integer; ACaption: String; ANotifyEvent: TNotifyEvent);
begin
  with TButton.Create(wizardform) do begin
    Left := ALeft;
    Top := ATop;
    Width := WizardForm.CancelButton.Width;
    Height := WizardForm.CancelButton.Height;
    Caption := ACaption;
    OnClick := ANotifyEvent;
    Parent := wizardform.welcomepage;
  end;
end;

Procedure LoadModuleButtonOnClick(Sender:Tobject);
begin
     LoadModule(Sender);
end;

Procedure InstallModuleButtonOnClick(Sender:TObject);
Var
     resultcode:integer;
begin
     //if Dir_Loaded=true then
     //begin
          //SourcePath:=FolderTreeView.Directory;
          //FolderTreeView.free;
          
          // Create the page
          Page := CreateInputFilePage(wpWelcome,
          'Select Module Location', 'Where is Module located?',
          'Select where Module is located, then click Next.');

          // Add item
          Page.Add('Location of Package Module:',         // caption
          'Package files|*.bpl',    // filters
          '.bpl');                                   // default extension

          // Set initial value (optional)
          //Page.Values[0] := ExpandConstant('{win}\notepad.exe');

          
          // Read value into variable
          
          dir_loaded:=true;

          //ShellExecAsOriginalUser('open','Copy '+sourcepath+'\*.* E:\Working Vicky\Midas Dr. Homs V3.0 - GRANDE\Setup\test /Y', '', '', SW_SHOWNORMAL, ewNoWait, ResultCode);
          //shellExec('Copy '+sourcepath+'\*.* E:\Working Vicky\Midas Dr. Homs V3.0 - GRANDE\Setup\test', '', '', SW_SHOWNORMAL, ewNoWait, resultcode);
          //SaveStringToFile('c:\tt.bat', 'Copy ', True);
     //end
     //else
     //begin
     //     msgbox('Please Load Module',mbInformation, MB_OK);
     //     exit;
     //end;
end;

procedure InitializeWizard();
var
  Left,Width, LeftInc, Top, TopInc: Integer;
begin
  Left := WizardForm.WelcomeLabel2.Left;
  LeftInc := WizardForm.CancelButton.Width + ScaleX(8);
  TopInc := WizardForm.CancelButton.Height + ScaleY(8);
  Top := WizardForm.WelcomeLabel2.Top + WizardForm.WelcomeLabel2.Height - 4*TopInc;
  
  //CreateButton(Left, Top+100, '&Load Module', @LoadModuleButtonOnClick);
  CreateButton(WizardForm.Welcomelabel2.left, WizardForm.CancelButton.Top-40, '&Install Module', @InstallModuleButtonOnClick);
  
  //Edit:=Tedit.Create(nil);
  //Edit.Top := WizardForm.WelcomeLabel2.Top + WizardForm.WelcomeLabel2.Height - 4*TopInc;
  //Edit.Left:=WizardForm.WelcomeLabel2.Left;
  //Edit.Width := WizardForm.Width div 2 - ScaleX(8);
  //Edit.Text := '';
  //Edit.Parent := WizardForm;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
     filename:string;
begin
     if dir_loaded=true then
     begin
          NotepadLocation := Page.Values[0];
          filename:=extractfilename(notepadlocation);
          filecopy(Notepadlocation ,'C:\Windows\apptem\'+filename,false);
          MsgBox('Module Installed'+#13+'Press Cancel to Exit or Back to Install more Module',Mbinformation,mb_ok);
          abort;
     end;
end;

function ShouldSkipPage(PageID: Integer): Boolean;
begin
   Log('ShouldSkipPage(' + IntToStr(PageID) + ') called');
  { Skip wpInfoBefore page; show all others }
  if dir_loaded=true then
  begin
  case PageID of
    6,8,9,10:
      Result := True;
  else
    Result := False;
  end;
  end;
end;

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
;Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked;

[Files]
Source: "..\Bin\MidasDrHomsV3_2.exe"; DestDir: "{app}";
;Source: "..\Bin\AcquireImage.exe"; DestDir: "{app}";
;Source: "..\Bin\Webcam.exe"; DestDir: "{app}";
Source: "..\Bin\DelphiTwainPackage.bpl"; DestDir: "{app}"; 
Source: "..\Bin\BarcodeD10.bpl"; DestDir: "{app}";
Source: "..\Bin\tmsd2010.bpl"; DestDir: "{app}";
Source: "..\Bin\tmsded2010.bpl"; DestDir: "{app}";
Source: "..\Bin\tmsexd2010.bpl"; DestDir: "{app}";  
Source: "..\Bin\Billing.bpl"; DestDir: "{app}";
Source: "..\Bin\CreditPayment.bpl"; DestDir: "{app}"; 
Source: "..\Bin\Registration.bpl"; DestDir: "{app}"; 
Source: "..\Bin\MidasFxnFraction.bpl"; DestDir: "{app}"; 
Source: "..\Bin\ChilKat.bpl"; DestDir: "{app}";
Source: "..\Bin\CorrectionAndModification.bpl"; DestDir: "{app}"; 
Source: "..\Bin\CommentSetup.bpl"; DestDir: "{app}"; 
Source: "..\Bin\DepartmentSetup.bpl"; DestDir: "{app}"; 
Source: "..\Bin\dex.bpl"; DestDir: "{app}"; 
Source: "..\Bin\DoctorSetup.bpl"; DestDir: "{app}"; 
Source: "..\Bin\Finding.bpl"; DestDir: "{app}"; 
Source: "..\Bin\PrivilegeSetup.bpl"; DestDir: "{app}"; 
;Source: "..\Bin\ExtendedFinding.bpl"; DestDir: "{app}";
Source: "..\Bin\FooterSetup.bpl"; DestDir: "{app}"; 
Source: "..\Bin\Global.bpl"; DestDir: "{app}"; 
Source: "..\Bin\CommunitySetup.bpl"; DestDir: "{app}"; 
Source: "..\Bin\CommunitySchemeSetup.bpl"; DestDir: "{app}";
Source: "..\Bin\ClinicalPathology.bpl"; DestDir: "{app}";
Source: "..\Bin\ClinicalHistology.bpl"; DestDir: "{app}"; 
;Source: "..\Bin\MedicalHistory.bpl"; DestDir: "{app}"; 
Source: "..\Bin\TestPackageSetup.bpl"; DestDir: "{app}";
Source: "..\Bin\MenuPrevilage.bpl"; DestDir: "{app}";
Source: "..\Bin\MidasFunction.bpl"; DestDir: "{app}"; 
Source: "..\Bin\Membership.bpl"; DestDir: "{app}"; 
Source: "..\Bin\NameModify.bpl"; DestDir: "{app}"; 
Source: "..\Bin\NewPatient.bpl"; DestDir: "{app}"; 
Source: "..\Bin\QR5RunD2010.bpl"; DestDir: "{app}"; 
Source: "..\Bin\RegAccount.bpl"; DestDir: "{app}"; 
Source: "..\Bin\RegisterMonitor.bpl"; DestDir: "{app}"; 
Source: "..\Bin\SchemeSetup.bpl"; DestDir: "{app}"; 
Source: "..\Bin\RemainingTest.bpl"; DestDir: "{app}"; 
Source: "..\Bin\Reports.bpl"; DestDir: "{app}"; 
Source: "..\Bin\VirtualTreesD14.bpl"; DestDir: "{app}";
Source: "..\Bin\VirtualTreesR14.bpl"; DestDir: "{app}";

;Source: "..\Bin\rtl140.bpl"; DestDir: "{app}"; 
Source: "..\Bin\SampleCollection.bpl"; DestDir: "{app}"; 
Source: "..\Bin\SampleRegister.bpl"; DestDir: "{app}"; 
Source: "..\Bin\SampleSourceSetup.bpl"; DestDir: "{app}"; 
Source: "..\Bin\SensitiveMedicineSetup.bpl"; DestDir: "{app}"; 
Source: "..\Bin\SensitiveMedicineTestWiseSetup.bpl"; DestDir: "{app}"; 
Source: "..\Bin\Test.bpl"; DestDir: "{app}"; 
Source: "..\Bin\TestNameSetup.bpl"; DestDir: "{app}"; 
Source: "..\Bin\ValidTestCancel.bpl"; DestDir: "{app}"; 
Source: "..\Bin\mailman.bpl"; DestDir: "{app}"; 
Source: "..\Bin\MachineIntegration.bpl"; DestDir: "{app}";
Source: "..\Bin\BloodBank.bpl"; DestDir: "{app}";
;Source: "..\Bin\vcl140.bpl"; DestDir: "{app}"; 
Source: "..\Bin\Verification.bpl"; DestDir: "{app}"; 
;Source: "..\Bin\WebBroadcast.bpl"; DestDir: "{app}"; 
Source: "..\BPL\adortl140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\CheckBoxGridd10.bpl"; DestDir: "{app}"; 
Source: "..\BPL\bdertl140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\CS30Inspectors70.bpl"; DestDir: "{app}"; 
Source: "..\BPL\DataSnapIndy10ServerTransport140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\DataSnapProviderClient140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\DataSnapServer140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\dbexpress140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\dbrtl140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\dbxcds140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\DBXClientDriver140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\DbxCommonDriver140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\DBXDb2Driver140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\DBXFirebirdDriver140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\DBXInformixDriver140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\DBXInterBaseDriver140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\DBXMSSQLDriver140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\DBXMySQLDriver140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\DBXOracleDriver140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\DBXSybaseASADriver140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\DBXSybaseASEDriver140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\dsnap140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\dsnapcon140.bpl"; DestDir: "{app}"; 
Source: "..\bIN\designide140.bpl"; DestDir: "{app}";
Source: "..\BPL\dss50.bpl"; DestDir: "{app}"; 
Source: "..\BPL\ibevnt140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\ibevnt140.bpl"; DestDir: "{app}";
Source: "..\BPL\SMCmpntD2010.bpl"; DestDir: "{app}"; 
Source: "..\BPL\ibxpress140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\CustomPrint.bpl"; DestDir: "{app}";
Source: "..\BPL\inet140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\inet50.bpl"; DestDir: "{app}"; 
Source: "..\BPL\inetdb140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\inetdb50.bpl"; DestDir: "{app}"; 
Source: "..\BPL\inetdbbde140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\inetdbxpress140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\Intraweb_100_140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\IntrawebDB_100_140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\nmfast50.bpl"; DestDir: "{app}"; 
Source: "..\BPL\qrpt50.bpl"; DestDir: "{app}"; 
Source: "..\BPL\rtl140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\rtl70.bpl"; DestDir: "{app}"; 
Source: "..\BPL\soaprtl140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\tee50.bpl"; DestDir: "{app}"; 
Source: "..\BPL\tee8140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\teedb50.bpl"; DestDir: "{app}"; 
Source: "..\BPL\teedb8140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\teeqr50.bpl"; DestDir: "{app}"; 
Source: "..\BPL\teeui50.bpl"; DestDir: "{app}"; 
Source: "..\BPL\teeui8140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vcl140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vcl50.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vcl70.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vclactnband140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vclado50.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vclbde50.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vcldb140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vcldb50.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vcldbx140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vcldbx50.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vclib140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vclib50.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vclie140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vclie50.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vclie70.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vclimg140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vcljpg50.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vclmid50.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vclribbon140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vclshlctrls140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vclsmp140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vclsmp50.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vcltouch140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vclx140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\vclx50.bpl"; DestDir: "{app}"; 
Source: "..\BPL\webdsnap140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\webmid50.bpl"; DestDir: "{app}"; 
Source: "..\BPL\websnap140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\xmlrtl140.bpl"; DestDir: "{app}"; 
;Source: "..\BPL\crcontrols140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\dac140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\dacvcl140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\datasetmanager140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\dclcrcontrols140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\dcldac140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\dclodac140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\dcloraprov140.bpl"; DestDir: "{app}"; 
Source: "..\BPL\odac140.bpl"; DestDir: "{app}";
Source: "..\BPL\odacvcl140.bpl"; DestDir: "{app}";
Source: "..\BPL\oraprov140.bpl"; DestDir: "{app}";



[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, "&", "&&")}}"; Flags: nowait postinstall skipifsilent


