unit DBGridExportToExcel;

interface

uses
     Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
     Dialogs, ComCtrls, StdCtrls, ExtCtrls, Grids, DBGrids, Buttons, jpeg, Menus,
     OleCtrls, excelxp, ComObj, DateEditXControl_TLB, DBCtrls, DB, DBTables, DBAccess, Ora, OraSmart, MemDS, OraError;

procedure ExportDBGrid(form: tform; dbgrid: TdbGrid; toExcel: Boolean; title, Date: string); Stdcall;

// **************************************************************************
// **************** UNIT CREATED BY VICKY PANDEY ****************************
// ****************  USING Memo FOR WINNT    ****************************
// ****************  FILE CREATED  17-APRIL-2011  06:25 PM ******************

// USES ComObj

// ADD THIS UNIT IN PROJECT AND CALL PROCEDURE ServiceRunnig();
// EG. Uses Services;
// procedure ButtonClick (Sender:Tobject);
// begin
// procedure ExportDBGrid(form_name,DbGrid,true,'Title');
// end;
// **************************************************************************
implementation

uses ServerDate, fxn;

procedure ExportDBGrid(form: tform; dbgrid: TdbGrid; toExcel: Boolean; title, Date: String); stdcall;
var
     bm: TBookmark;
     col, row, viscol: Integer;
     sline, Str: String;
     mem: TMemo;
     ExcelApp, ColumnRange: OleVariant;
     colname: string;
     Qry: TOraQuery;
     TotalRec:Integer;
begin
     Screen.Cursor := crHourglass;
     dbgrid.DataSource.DataSet.DisableControls;
     bm := dbgrid.DataSource.DataSet.GetBookmark;
     dbgrid.DataSource.DataSet.First;

     // create the Excel object
     if toExcel then
     begin
          ExcelApp := CreateOleObject('Excel.Application');
          ExcelApp.WorkBooks.Add(xlWBatWorkSheet);
          ExcelApp.WorkBooks[1].WorkSheets[1].Name := title;
     end;

     // First we send the data to a memo
     // works faster than doing it directly to Excel
     with form do
     begin
          mem := TMemo.Create(nil);
          mem.Visible := false;
          mem.Parent := form;
          mem.Clear;
          sline := '';

          // adding header
          mem.Lines.Add(gs_HospitalName);
          mem.Lines.Add(title);
          mem.Lines.Add('Date: ' + Date);
          mem.Lines.Add('');
          mem.Lines.Add('Generated By: ' + gs_UserName + ':: Date:' + TodaysDate + ' :: Time: ' + TodaysTime);
          mem.Lines.Add('');

          // visible columns viscol
          viscol := 0;

          // add sno
          sline := 'SNo.' + #9;
          viscol := 1;
          // add the info for the column names
          for col := 0 to dbgrid.FieldCount - 1 do
          begin
               if dbgrid.Columns[col].Visible then
               begin
                    sline := sline + dbgrid.Columns[col].title.Caption + #9;
                    if viscol < 26 then
                         colname := chr(viscol + 97)
                    else if (viscol >= 26) and (viscol < 52) then
                         colname := 'a' + chr(viscol - 26 + 97)
                    else if (viscol >= 52) and (viscol < 78) then
                         colname := 'b' + chr(viscol - 52 + 97);
                    viscol := viscol + 1;
               end;
          end;
          mem.Lines.Add(sline);
          TotalRec:=0;
          While not dbgrid.DataSource.DataSet.Eof do
          begin
               sline := inttostr(row + 1) + #9;
               for col := 0 to dbgrid.FieldCount - 1 do
               begin
                    if dbgrid.Columns[col].Visible then
                    begin
                         Try
                              Str := dbgrid.Fields[col].AsString;
                         Except
                              Str := '';
                         End;
                         Str := StringReplace((Str), '#13', '', [rfReplaceAll]);
                         sline := sline + Str + #9;
                    end;
               end;
               mem.Lines.Add(sline);
               dbgrid.DataSource.DataSet.Next;
               Inc(TotalRec);
               Inc(row);
          end;
          // get the data into the memo
          // for row := 0 to TStringGrid(dbgrid).RowCount do
          // begin
          // sline := inttostr(row+1)+#9;
          // for col := 0 to DbGrid.FieldCount-1 do
          // begin
          // if dbgrid.Columns[col].Visible then
          // begin
          // Try
          // Str:=DbGrid.Fields[col].AsString;
          // Except
          // Str:='';
          // End;
          // Str:= StringReplace((Str),'#13','',[rfReplaceAll]);
          // sline := sline + Str+ #9;
          // end;
          // end;
          // mem.Lines.Add(sline);
          // DbGrid.DataSource.DataSet.Next;
          // end;

          // we copy the data to the clipboard
          mem.SelectAll;
          mem.CopyToClipboard;

          // if needed, send it to Excel
          // if not, we already have it in the clipboard
          if toExcel then
          begin
               ExcelApp.WorkBooks[1].WorkSheets[title].Paste;
               ExcelApp.Visible := true;
               ExcelApp.Range['A1:' + colname + '1'].Mergecells := true;
               ExcelApp.Range['A1:' + colname + '1'].font.bold := true;
               ExcelApp.Range['A1:' + colname + '1'].HorizontalAlignment := xlcenter;
               ExcelApp.Range['A2:' + colname + '2'].Mergecells := true;
               ExcelApp.Range['A2:' + colname + '2'].HorizontalAlignment := xlcenter;
               ExcelApp.Range['A2:' + colname + '2'].font.color := clRed;
               ExcelApp.Range['A3:' + colname + '3'].Mergecells := true;
               ExcelApp.Range['A3:' + colname + '3'].HorizontalAlignment := xlcenter;
               ExcelApp.Range['A4:' + colname + '4'].Mergecells := true;
               ExcelApp.Range['A4:' + colname + '4'].HorizontalAlignment := xlcenter;
               ExcelApp.Range['A5:' + colname + '5'].Mergecells := true;
               ExcelApp.Range['A5:' + colname + '5'].HorizontalAlignment := xlleft;
               ExcelApp.Range['A6:' + colname + '6'].Mergecells := true;
               ExcelApp.Range['A6:' + colname + '6'].HorizontalAlignment := xlcenter;
               ExcelApp.Range['A7:' + colname + '7'].font.bold := true;

               // apply autofit to entire columns
               ExcelApp.Range['A7:' + colname + '7'].EntireColumn.Autofit;

               // Apply Border
               for row := 7 to TotalRec + 7 do
               begin
                    ExcelApp.Range['A' + inttostr(row) + ':' + colname + inttostr(row)].Borders.Weight := xlThin;
                    ExcelApp.Range['A' + inttostr(row) + ':' + colname + inttostr(row)].Borders.color := clteal;
                    if row = 7 then
                    begin
                         ExcelApp.Range['A' + inttostr(row) + ':' + colname + inttostr(row)].font.color := clwhite;
                         ExcelApp.Range['A' + inttostr(row) + ':' + colname + inttostr(row)].Interior.color := clteal;
                         ExcelApp.Range['A' + inttostr(row) + ':' + colname + inttostr(row)].Borders.color := clblack;
                    end;
               end;

               // Fit to X page(s) wide by Y tall
               ExcelApp.ActiveSheet.PageSetup.FitToPagesWide := 1; // Y
               ExcelApp.ActiveSheet.PageSetup.FitToPagesTall := 3; // Y

               // Set Black & White
               // ExcelApp.ActiveSheet.PageSetup.BlackAndWhite := true;

          end;

          // FreeAndNil(ExcelApp);
          dbgrid.DataSource.DataSet.GotoBookmark(bm);
          dbgrid.DataSource.DataSet.FreeBookmark(bm);
          dbgrid.DataSource.DataSet.EnableControls;
          Screen.Cursor := crDefault;
     end;
end;

Exports ExportDBGrid;

end.
